### ISSUE TITLE
Update to be compatible with rspec 3?

### ISSUE THREAD

**Issue by TonyLovesDevOps** [juliandunn/library-demo-cookbook#2]
This example was just what I was looking for - unfortunately it looks like the code isn't compatible with rspec 3 (which is included with chefdk). See output below of an rspec run.

Any chance this could be updated to the new syntax?

```
$ rspec -v
3.3.0

$ rspec spec
FFF

Failures:
  1) Demo::Helper#has_bacon? builds the correct command
     Failure/Error: expect(dummy_class.new.has_bacon?).to be_false
       #<Double (anonymous)> received unexpected message :live_stream with (no args)
     # ./libraries/demo_helper.rb:7:in `has_bacon?'
     # ./spec/unit/helper_spec.rb:33:in `block (3 levels) in <top (required)>'

  2) Demo::Helper#has_bacon? without bacon says there is no bacon
     Failure/Error: expect(dummy_class.new.has_bacon?).to be_false
       #<Double (anonymous)> received unexpected message :live_stream with (no args)
     # ./libraries/demo_helper.rb:7:in `has_bacon?'
     # ./spec/unit/helper_spec.rb:42:in `block (4 levels) in <top (required)>'

  3) Demo::Helper#has_bacon? with bacon says there is bacon
     Failure/Error: expect(dummy_class.new.has_bacon?).to be_true
       #<Double (anonymous)> received unexpected message :live_stream with (no args)
     # ./libraries/demo_helper.rb:7:in `has_bacon?'
     # ./spec/unit/helper_spec.rb:52:in `block (4 levels) in <top (required)>'

Deprecation Warnings:

Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Cal
led from /tmp/library-demo-cookbook/spec/unit/helper_spec.rb:27:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 0.07501 seconds (files took 3.09 seconds to load)
3 examples, 3 failures

Failed examples:

rspec ./spec/unit/helper_spec.rb:30 # Demo::Helper#has_bacon? builds the correct command
rspec ./spec/unit/helper_spec.rb:40 # Demo::Helper#has_bacon? without bacon says there is no bacon
rspec ./spec/unit/helper_spec.rb:50 # Demo::Helper#has_bacon? with bacon says there is bacon


  No Chef resources found, skipping coverage calculation...
```

**Comment by juliandunn** [comment]
I don't have time for that, but I'd take a patch for sure! Thanks.
